### ISSUE TITLE
Malicious code?

### ISSUE THREAD

**Issue by aManwithaPlan32** [hugemenace/nd#111]
I scanned the zip on virustotal, here's the scan: https://www.virustotal.com/gui/url/b7210c78b35b5f25beb710b250b616deb726f1039e089f0c38ec59666a8c7288

**Comment by tristan-hm** [comment]
**Short answer:** It's a false positive (the ND codebase does not contain anything malicious). It's likely due to the response headers from GitHub's server when you do a direct URL scan. If you download the ND zip file and run it through VirusTotal, there are no issues: https://www.virustotal.com/gui/file/0b19be005d33345d3718996f8ff8629f8c6e9dc7293982a9780c93c6c4764760

**Long answer:** I've written every line of code for ND, and I assure you nothing malicious has been added. But you don't just have to take my word for it; the ND codebase is entirely open-source (all hosted here on GitHub), and there are no precompiled binaries or obfuscated code. You or anyone else is welcome to go through and check every single line of code and verify my statement. I'm also happy to answer any questions or clarify what any particular part of the codebase is doing if you need help understanding it :)
