### ISSUE TITLE
Add mouse value support to all currently unsupported operator options (e.g., screw head type)

### ISSUE THREAD

**Issue by luckychris** [hugemenace/nd#74]
I don't get other screw types...

https://user-images.githubusercontent.com/232549/200291714-40b0e0fd-3cbd-4c76-b74e-3db4a0a06e7e.mov

here my settings:

<img width="870" alt="image" src="https://user-images.githubusercontent.com/232549/200291807-0c3f0240-e03d-4e20-b278-9130d35a13d7.png">

**Comment by tristan-hm** [comment]
Thanks for the report. Can you change the screw head types by scrolling or hitting the up/down arrow keys?

**Comment by luckychris** [comment]
Yes, arrow keys work, but no way by using my touchpad to change it by that - and i would prefer that, because this is the fastest way. But a small remark: if it still says "browsing" although it works - is a bit misleading ;) but thanks for the arrow hint! I appreciate that.

**Comment by tristan-hm** [comment]
Thanks, I just wanted to verify if the issue on your end was input-related (scroll vs keyboard) or if the operator was having trouble loading the screw heads from the source `.blend` file.

This issue is relatively straightforward to fix. However, it's part of a more extensive update to add mouse-value support to many fields that previously only supported "scroll" or up/down arrow key selection. You'll notice how a handful of operator options don't yet support direct mouse-value (movement) support, for example, the screw head operator: https://docs.nd.hugemenace.co/#/sketch/screw-head (but for all those that don't, the up/down arrow keys will still work).

I'll prepare an update across the board and perhaps change the "Browsing..." label while I'm at it :)

**Comment by luckychris** [comment]
that's great!!

**Comment by luckychris** [comment]
i just downloaded the newest version and it works like a charm!!! Thanks for that update!!!

**Comment by tristan-hm** [comment]
No problem :) It'll be included in the next formal release (1.36.0) once it's ready; otherwise, feel free to use this repo directly (`git clone` in your Blender add-ons folder) to stay up to date with development.
